on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y jq
      - uses: actions/checkout@v4.1.1
      - name: Validate user_map.json
        run: bash .github/workflows/test.sh
